apiVersion: iam.aws.jet.crossplane.io/v1alpha2
kind: OpenIDConnectProvider
metadata:
  name: example
spec:
  forProvider:
    clientIdList:
    - <clientID>
    thumbprintList:
    - <thumbprint>
    url: https://accounts.google.com
  providerConfigRef:
    name: example