apiVersion: globalaccelerator.aws.jet.crossplane.io/v1alpha2
kind: Accelerator
metadata:
  name: sample-accelerator
spec:
  forProvider:
    ipAddressType: "IPV4"
    name: sample-accelerator
    region: eu-west-1
  writeConnectionSecretToRef:
    name: accelerator
    namespace: default
