apiVersion: globalaccelerator.aws.jet.crossplane.io/v1alpha2
kind: EndpointGroup
metadata:
  name: sample-endpoint-group
spec:
  forProvider:
    listenerArnRef:
      name: sample-listener
  writeConnectionSecretToRef:
    name: accelerator
    namespace: default
