apiVersion: globalaccelerator.aws.jet.crossplane.io/v1alpha2
kind: Listener
metadata:
  name: sample-listener
spec:
  forProvider:
    acceleratorArnRef:
      name: sample-accelerator
    clientAffinity: "SOURCE_IP"
    protocol: "TCP"
  writeConnectionSecretToRef:
    name: accelerator
    namespace: default
